/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftMarketplaceSol from "./NftMarketplace.sol";
export type { nftMarketplaceSol };
export type { NFTMarketplaceOld } from "./NFTMarketplaceOld";
